apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: vat
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      git-branch: master
    creationTimestamp: null
    generation: 3
    labels:
      app: vat
      ENV: ${ENV}
      component: frontend
    name: vat-${ENV}
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: vat
      ENV: ${ENV}
      component: frontend
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          git-branch: master
        creationTimestamp: null
        labels:
          app: vat
          ENV: ${ENV}
          component: frontend
      spec:
        containers:
        - image: docker-registry.default.svc:5000/viaa-tools/vat:${ENV}
          imagePullPolicy: Always
          name: vat
          envFrom:
            - configMapRef:
                name: vat-${ENV}
          ports:
          - containerPort: 1234
            name: http
            protocol: TCP
          resources: {}
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsUser: 1000
        terminationGracePeriodSeconds: 10
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - vat-${ENV}
        from:
          kind: ImageStreamTag
          name: vat:latest
          namespace: viaa-tools
        lastTriggeredImage:
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      git-branch: master
    creationTimestamp: null
    labels:
        app: vat
        ENV: ${ENV}
        component: frontend
    name: vat-${ENV}
  spec:
    ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: vat
      ENV: ${ENV}
      component: frontend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
  - name: ENV
    value: dev
