apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: vat
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      git-branch: master
    creationTimestamp: null
    generation: 3
    labels:
      app: vat
      ENV: ${ENV}
      component: frontend
    name: vat-${ENV}
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: vat
      ENV: ${ENV}
      component: frontend
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          git-branch: master
        creationTimestamp: null
        labels:
          app: vat
          ENV: ${ENV}
          component: frontend
      spec:

        containers:
            - envFrom:
                - configMapRef:
                    name: vat-qas
            image: >-
                docker-registry.default.svc:5000/viaa-tools/vat@sha256:bd3c48ee37e855d7b73980eaf927a83ad932a7517ef8c65fa93a176583146550
            imagePullPolicy: Always
            livenessProbe:
                failureThreshold: 3
                httpGet:
                path: /
                port: 8080
                scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 12
            name: vat
            ports:
                - containerPort: 8080
                name: http
                protocol: TCP
            readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 50
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                port: 8080
                timeoutSeconds: 12
            resources:
                limits:
                cpu: 300m
                memory: 512Mi
                requests:
                cpu: 200m
                memory: 164Mi
            securityContext:
                privileged: false
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
            runAsUser: 101
        terminationGracePeriodSeconds: 10
    test: false
    triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
            - vat
            from:
            kind: ImageStreamTag
            name: 'vat:${ENV}'
            namespace: viaa-tools
            lastTriggeredImage: >-
            docker-registry.default.svc:5000/viaa-tools/vat@sha256:bd3c48ee37e855d7b73980eaf927a83ad932a7517ef8c65fa93a176583146550
        type: ImageChange
        - type: ConfigChange
        
    
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      git-branch: master
    creationTimestamp: null
    labels:
        app: vat
        ENV: ${ENV}
        component: frontend
    name: vat-${ENV}
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: vat
      ENV: ${ENV}
      component: frontend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
  - name: ENV
    value: qas
